# Generated by Django 5.2.9 on 2025-12-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('currency', models.CharField(max_length=10)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('source', models.CharField(default='BCM', max_length=100)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date', 'currency')},
            },
        ),
    ]
